### ISSUE TITLE
toontown fellowship on wine

### ISSUE THREAD

**Issue by mgracer48** [toontownfellowship/src#100]
Stuck on a white screen  Wont even load loading screen

**Comment by Loudrob** [comment]
this isnt a fixable issue until a native mac launcher is released

**Comment by mgracer48** [comment]
yea yea uh huh

**Comment by lordperiwkle** [comment]
When I first came here, I worked a week with no disconnections or stalls.  However, of recent, I am finding the same problems as TTR is having.  Is it the population increase or something glitch in the server for game player connected.  I'm confused and a bit dismayed over the same problems that brought me here.  Please find and fix it, okay.

**Comment by MiniguyBrendan** [comment]
This is fixable. You need to enable X11 in Wine.
