### ISSUE TITLE
mgracer48's pull requests

### ISSUE THREAD

**Issue by nkrypt** [toontownfellowship/src#111]
Someone needs to make sure they are clean before merging.

**Comment by kevman95** [comment]
Yes. 100% Agree.

**Comment by judge2020** [comment]
^^^

**Comment by mgracer48** [comment]
....

**Comment by mgracer48** [comment]
i call this bullying

**Comment by mgracer48** [comment]
you know i can improve :/ just give me a break

**Comment by mgracer48** [comment]
someone please close this issue

**Comment by pslifeisgood** [comment]
Nobody close it

**Comment by mgracer48** [comment]
why not this is rude

**Comment by judge2020** [comment]
This should be closed. I agree that his PR's are one line cancer commits, but there also haven't been rules posted since the repo was forked, so he wasn't doing anything wrong.

**Comment by mgracer48** [comment]
thank you! i will try to improve my commits

**Comment by Loudrob** [comment]
Enigmeow the doc-master will probably make rules.

**Comment by pslifeisgood** [comment]
He better, and fast. I don't need more people like Michael here making these commits

**Comment by MiniguyBrendan** [comment]
_
           /(|
          (  :
         __\  \  _____
       (____)  `|
      (____)|   |
       (____).__|
        (___)__.|_____

**Comment by CrazyClyde** [comment]
They're funny how bad they are. Especially the "make an exception if building client fails" one, where he only has an "exception:" without a "try:". I literally died laughing from that one.

**Comment by MiniguyBrendan** [comment]
@CrazyClyde  I think it was an "else" without an "if" but yeah
