### ISSUE TITLE
Bug: During Toon-torial, Tutorial Tom doesn't show up and tells player to go to HQ.

### ISSUE THREAD

**Issue by ToontownLittleCat** [toontownfellowship/src#120]
Title and gif says it all.

![](http://i.gyazo.com/52008016518bf04078143fa6cd5486e3.gif)

**Comment by judge2020** [comment]
This is because Tom would have invisible legs :P

**Comment by ToontownLittleCat** [comment]
But still, this needs to be fixed first.

**Comment by Spiderlover** [comment]
well, on my own version of Toontown Fellowship, I didn't even get the Toon-torial after creating my toon, The game skipped me to TTC with the Trolley Task complete.

**Comment by ToontownLittleCat** [comment]
@Spiderlover That because "force-skip-tutorial"option is enabled on
dev.prc.  Set that to false, make a new toon, and voila!

**Comment by Spiderlover** [comment]
@ToontownLittleCat ok, thanks for the help :)

**Comment by enigmeow** [comment]
Pulled this into a branch for testing
