### ISSUE TITLE
Pull Requests Getting Buried and Ignored

### ISSUE THREAD

**Issue by Spiderlover** [toontownfellowship/src#123]
Due to mgracer48's silly pull requests from the past couple of days, better and more important pull requests are getting buried and ignored by the Toontown Fellowship Staff. These pull requests are more useful to the game, because they fix stuff or add stuff to the game.

These pull request numbers are 9, 12, 62, 68, 79, 97, 112, 115, 117, and 118

The pull request, 9, was submitted by me 29 days ago, and it still hasn't been merged. I recently updated the pull requests by fixing the wording for the dialogue in the new Toon Task that I added.

**Comment by Chandler255** [comment]
@Spiderlover Thank you for bringing this to our attention, we will definitely take a look at the pull requests you have listed.

**Comment by enigmeow** [comment]
I've begun to pull the various requests into local branches to allow testing and local debate..  I will continue doing this and then we can start having some formal debates.. :)

**Comment by Spiderlover** [comment]
ok, thank you :)

**Comment by enigmeow** [comment]
Fixed

**Comment by mgracer48** [comment]
@Spiderlover lol i remember this XD

**Comment by gamesawdrew** [comment]
@mgracer48 u still do that. just not as pull requests. u just add tem into the game ur self

**Comment by mgracer48** [comment]
@gamesawdrew no i don't
