### ISSUE TITLE
Old Shard Page buttons.

### ISSUE THREAD

**Issue by gabrielfraser223** [toontownfellowship/src#135]
How do I bring back the old buttons? Do you mind posting a link to where I can restore these buttons as the numbers make the shard page looking un-natural.

Cheers,  
Gabriel.

**Comment by Wilee999** [comment]
you need to downgrade panda to 1.4.1 and python to 2.3 it should work then... the panda upgrades improved it

**Comment by gabrielfraser223** [comment]
Is that a troll? Cause the game was built for 1.9.0 panda3d.

**Comment by CrazyClyde** [comment]
No, @Wilee999 is one of the most intelligent and most serious people in the Toontown community, trust him.

**Comment by Wilee999** [comment]
i disagree with that statement because it included more than one comma

**Comment by judge2020** [comment]
Wow

**Comment by CrazyClyde** [comment]
@Wilee999 Sorry I'll Make Sure To Bug Fix My Sentences ! ! !
