### ISSUE TITLE
Add more than 1 safeHarbour? [RPC]

### ISSUE THREAD

**Issue by gabrielfraser223** [toontownfellowship/src#136]
I've tried many things like:

safeHarbours{"shard1" , "shard2"}

P.S shard1/shard2 are examples.

**Comment by judge2020** [comment]
Do I smell a @mgracer48 clone?

**Comment by gabrielfraser223** [comment]
Sorry lol. I ask questions then I usually figure out the issue. I'm kinda stupid like that. :P
