### ISSUE TITLE
Random DC every hour?

### ISSUE THREAD

**Issue by brownzilla** [toontownfellowship/src#149]
Hey TTF Team...

I host a server and every hour it kicks all toons off. This has been an issue that is more of an annoyance then a bug.

I'm not sure if this is a CPU or RAM issue it just kicks toons every hour.

I'll post my server specs below.

Server SPECS:
Windows Server 2008 R2 with Virtio Drivers Installed
1x Intel Xeon 3.4GHZ CPU Core
1GB DDR3 RAM
20GB SSD 6.2gbps
10 gbps uplink speed

Thanks, 
Gabriel

**Comment by judge2020** [comment]
I'm not sure what this could be caused by, but I do say that even though you have a beast processor that's made for 24/7 operation, your ram is very bad. This could be the problem, but don't hold me to it.

**Comment by enigmeow** [comment]
What is your swap set at? With that small a disk, I would bet the virtual memory is set pretty small as well.  I had this issue when I was running on a small virtual machine for a while.

But honestly, we don't run this in production on a windows box and so we have no experience with long term stability on that platform.  Sorry

**Comment by gabrielfraser223** [comment]
Okay so I should wait for you guys to finish writing up the Linux tutorial. My native OS is Linux. I'm a windows noob. Haha.

**Comment by gabrielfraser223** [comment]
@judge2020 I've tried running the server with 2GB ram and it uses less than a gig but I still get random  disconnections every hour. I've also tried to see if the time is the issue due to it being every hour.

**Comment by judge2020** [comment]
I have been working on a Linux tutorial but I am having trouble with installing panda on it, lots of dependency issues, but hopefully it'll be out soon

**Comment by enigmeow** [comment]
https://github.com/toontownfellowship/src/blob/master/doc/production/README

**Comment by gabrielfraser223** [comment]
@judge2020 I've compiled Panda3D-1.9.0 on linux? I could link you a link. I've successfully installed panda3d on my ubuntu OS

**Comment by gabrielfraser223** [comment]
@enigmeow I've got everything to run. I'm just having issues with the astrond not working and the ai_server is having a python27 error which is fixable.
