### ISSUE TITLE
Infinite Cipher?

### ISSUE THREAD

**Issue by gabrielfraser223** [toontownfellowship/src#160]
hey...

You have probably been asked this a lot lately but when is the infinite cipher being released? I really want to get a server going for my friends and I. 

Thanks, 
Gabriel.

**Comment by judge2020** [comment]
Infinite cypher is the only remote security the TTI based servers have against hackers is what I believe. So unless a Dev goes crazy, it's not going to be released

**Comment by daviddave** [comment]
Hey. Why don't you try using tto as a base line and make a ,bat to run it. I got it updating from toontown.exe. Working on a launcher but fails.

**Comment by gabrielfraser223** [comment]
daviddave, wanna work together? I'm currently working on a launcher aswell and it works

**Comment by daviddave** [comment]
yeah. Im working on a copy like original tto.

**Comment by CrazyClyde** [comment]
Can I help @daviddave  ?

**Comment by gabrielfraser223** [comment]
Daviddave, message me your skype details, I'll come join development. I'll send you my skype anyway. haha @daviddave

**Comment by daviddave** [comment]
@crazyclyde yes. So you know I'm in England so. I'm off to school. @gabrialfraser223 I got your message. I'll message you tonight on skype.

**Comment by mgracer48** [comment]
@daviddave if you want to help a game with making a launcher please message me back we need some help!

**Comment by gamesawdrew** [comment]
@mgracer48 yes we do :)

**Comment by mgracer48** [comment]
@daviddave  just message me on skype im mgracer

**Comment by daviddave** [comment]
there's several

**Comment by mgracer48** [comment]
what about mgracer48?

**Comment by gamesawdrew** [comment]
@daviddave Add me on skype, im Xysda12345. I have MGRACER, i will send u his contact if you want :)

**Comment by Loudrob** [comment]
sigh....

**Comment by pslifeisgood** [comment]
Goodluck with getting their AI files homos ;)

**Comment by Loudrob** [comment]
i hope they realize that it isnt possible to add new content if its all in the .exe..

**Comment by daviddave** [comment]
Who are you talking to

**Comment by gabrielfraser223** [comment]
@Loudrob, I'm making a toontown server with @daviddave and so far we've got the launcher to run, download, and connect to the server. That is using the old toontown launcher. You would be surprised how much effort we're putting in.

**Comment by pslifeisgood** [comment]
That doesn't sound like much effort @gabrielfraser223

**Comment by CrazyClyde** [comment]
@pslifeisgood No I'm fairly sure them using 4 lines of TTInjector code to get fire hydrant animations "working" is alot of effort.

**Comment by gamesawdrew** [comment]
@CrazyClyde I would love to get those hydrant animations working ;)

**Comment by CrazyClyde** [comment]
@gamesawdrew It's only in the emulator that they're using, and even though it literally is 4 short lines of code they'll probably never figure it out.

**Comment by judge2020** [comment]
the only possible way you could add new content is having the launcher inject something at the startup, but then someone could modify what it injects :P

**Comment by daviddave** [comment]
Build_client.py

**Comment by judge2020** [comment]
@daviddave what do you mean?

**Comment by daviddave** [comment]
have it build a .dll not a .bin

**Comment by CrazyClyde** [comment]
@daviddave In my opinion that's basically impossible, considering you'd have to convert all the code to C/C++... (or Cython)

**Comment by Loudrob** [comment]
@CrazyClyde you are wrong.

**Comment by CrazyClyde** [comment]
@Loudrob ???

**Comment by gabrielfraser223** [comment]
He's actually right lol. Frozen code can be compiled into *.dll

**Comment by Loudrob** [comment]
build_client can't be used since you guys will never get infinitecipher

**Comment by Loudrob** [comment]
close this issue please, you guys can talk about this in your own repo, not this issue

**Comment by ToontownLittleCat** [comment]
@Loudrob is right, it is very unlikely for infinite cipher to be released to the public.  If you like to freeze your client code for the public, you have to figure that out yourself.  Closing.

**Comment by pslifeisgood** [comment]
Y'all crazy
