### ISSUE TITLE
Walking in petshop

### ISSUE THREAD

**Issue by gamesawdrew** [toontownfellowship/src#161]
Whenever i enable pets, when i walk into the pet shop, i start to walk in, but once the door opens, it teleports me to the coords 0,0 and i get stuck. is it something with the DNA file or part of the code?

**Comment by gamesawdrew** [comment]
This is what it looks like: http://gyazo.com/5e0f4bf84464e8a64494d21ee21db7c2

**Comment by judge2020** [comment]
This is because the pet shop code is set tp you to 0,0 because the pet shop code isn't properly implemented. To get this to work, you'll need to code the pets yourself and remove the 0,0 TP code

**Comment by judge2020** [comment]
I'm pretty sure [this](https://github.com/toontownfellowship/src/blob/master/toontown/building/DistributedPetshopInteriorAI.py) is the file that TPs you back and requires coding

**Comment by gamesawdrew** [comment]
That's weird. cuz in the very old TTI retro version thing, i was able to get in, and i just checked and the code is the same...

**Comment by nkrypt** [comment]
@judge2020 No, the door origin is messed up.

**Comment by gamesawdrew** [comment]
@nkrypt Is that in the dna files?

**Comment by nkrypt** [comment]
@gamesawdrew No, it's the model itself.

**Comment by gamesawdrew** [comment]
@nkrypt Oh. Maybe i can use the working model, and that should fix?

**Comment by nkrypt** [comment]
@gamesawdrew Go back a few commits on resources and that should fix it, before Sean pushed something with pet shop models.

**Comment by gamesawdrew** [comment]
@nkrypt Ok, i can enter the shop now :D. Thank you so much!
