### ISSUE TITLE
Compiling to PYD

### ISSUE THREAD

**Issue by MikeTheToon** [toontownfellowship/src#162]
Hey there! I was wondering how to compile to pyd and run it. I already prepared the client. I am just having an error with the build tools. Could anyone help me out? If you need my skype it is miketoontown.
```
couldn't import shared
Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Panda3D-1.8.1\direct\showutil\pfreeze.py", line 72, in <module>
    freezer.addModule(module)
  File "C:\Panda3D-1.8.1\direct\showutil\FreezeTool.py", line 776, in addModule
    for dirname in self.getModulePath(topName):
TypeError: 'NoneType' object is not iterable
Done building the client.
```

**Comment by judge2020** [comment]
Maybe this is because you're using Panda 1.8.1? Fellowship uses a custom panda 1.9 build that includes some tools and whatnot (just like infinite) but there's probably also something else...

**Comment by judge2020** [comment]
Btw the panda is located in the third party repo of this github organization

**Comment by MikeTheToon** [comment]
Okay so, I have gotten the pyd to work but I am trying to run the game. I recompiled the pyd in 1.9.0 and it worked. So I am trying to run it with this code:
Batch file:
```
@echo off




set /P Username="Username: "

set PLAYCOOKIE=%Username%

C:\Panda3D-1.9.0\python\ppython -m StartGame.pyc
pause
```
And the PYC File:
```
print 'Starting game'

import sys
sys.path.append("/")

import GameData
import toontown.toonbase.ClientStartDist
```
The error I get is:
```
C:\Panda3D-1.9.0\python\ppython.exe: dynamic module does not define init functio
n (initlibpandaexpress)
```

**Comment by judge2020** [comment]
```does not define init function 
```
looks like there is no __init__ file or in initlibpandaexpress the __init__ function isn't there

**Comment by MikeTheToon** [comment]
How would I fix that ^_^



..

._.

**Comment by flumes** [comment]
Python *.pyd files, like *.dll files, have a module to execute on load. Do not hard code the client start module. Use the --main-module argument properly and on loading the library the client start module will start automatically. I believe you're getting this error because the *.pyd was not given an objective (i.e. you did not define the main module or the one used did not exist). If the issue persists, make sure you are using the correct revision of Panda3D.

**Comment by MikeTheToon** [comment]
@flumes 
The main-module is defined. I am using Panda 3D 1.8.1 for the build tools, and the game. When I use 1.8.1 I get this error:

```
Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Panda3D-1.8.1\python\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Panda3D-1.8.1\python\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Panda3D-1.8.1\python\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "StartGame.py", line 7, in <module>
    import toontown.toonbase.ClientStart
  File "toontown.toonbase.ClientStart", line 102, in <module>
  File "toontown.toonbase.ToonBase", line 66, in __init__
ZeroDivisionError: float division by zero
```

**Comment by judge2020** [comment]
@mikethetoon did you even read the earlier messages?
"Maybe this is because you're using Panda 1.8.1? Fellowship uses a custom panda 1.9 build that includes some tools and whatnot (just like infinite) but there's probably also something else..."

**Comment by judge2020** [comment]
The 1.9 build TTF uses is in the third party repo

**Comment by MikeTheToon** [comment]
@judge2020 
I did read the earlier messages and I tried to see if 1.8.1 work work but apparently not. 1.9 is still the same error with the module defined.
