### ISSUE TITLE
I like pussy

### ISSUE THREAD

**Issue by JoeyZiolkowski** [toontownfellowship/src#169]
Yea its good

**Comment by JoeyZiolkowski** [comment]
All hail fucking Maverick boys.

**Comment by Spiderlover** [comment]
All Hail the Mighty Dark Lord of the Sith, Maverick

**Comment by JoeyZiolkowski** [comment]
DAMN ME I SUCK

**Comment by Spiderlover** [comment]
Don't worry, Joey, you will be a real Python coder, one day :)

**Comment by JoeyZiolkowski** [comment]
Thanks I know I will but also why did i get removed from TTR github? They hate me :(

**Comment by Spiderlover** [comment]
awwww, that's too bad
