### ISSUE TITLE
Enhancement: Limit teleport requests

### ISSUE THREAD

**Issue by judge2020** [toontownfellowship/src#31]
Teleport requests should be limited. Perhaps one teleport request every 1-3 seconds? This would help prevent spam. Furthermore, if a request is currently active, another shouldn't be issued. This will prevent teleport spam.

[xpythonic with the original issue](https://github.com/ToontownInfinite/src/issues/227)

**Comment by chandler14362** [comment]
Teleport requests already have a limit on them
