### ISSUE TITLE
Dev window shows TTI logo

### ISSUE THREAD

**Issue by judge2020** [toontownfellowship/src#45]
![image](http://i.gyazo.com/b965ccf66580e99f619c77b97bfeb554.png)

**Comment by Puggyblue999** [comment]
That can be easily fixed, they just need a new logo to change it to and replace the favicon in phase_3/etc/icon.ico

**Comment by judge2020** [comment]
@Puggyblue999 I can't seem to multify the phase_3 the launcher uses right now so i'm unable to get the image

**Comment by Wilee999** [comment]
they didnt even change it after tti changed their logo

**Comment by gamesawdrew** [comment]
they didnt change the logo because the tti game logo was that, and thats what their code had atleast

**Comment by Loudrob** [comment]
@gamesawdrew It was only that for 2 weeks, and then it was the one that looked like deformed red lips. But they still, for some reason, hadn't changed it.

**Comment by judge2020** [comment]
@loudrob @gamesawdrew it's just the Dev window so they don't care... It's not the public window logo :P

**Comment by gamesawdrew** [comment]
@judge2020 @loudrob ya thats kind of what i meant, the logo was that because that was the dev logo
