### ISSUE TITLE
special toontask: Recieve the "Name your toon!" button

### ISSUE THREAD

**Issue by judge2020** [toontownfellowship/src#47]
A just-for-fun task that gives you this button upon completion
![image](http://i.gyazo.com/dd889294950210cbbf8ba37a14f67202.jpg)

**Comment by ttcloopy** [comment]
No, no no no... Just No.  Pick your name, stay with your name.  Changing toon names will cause far to many issues in moderating the game.  Changing toon color is bad enough!

**Comment by Loudrob** [comment]
@ttcloopy Toon still have the same avIds even after renaming, so it shouldn't be too much of an issue. I think that something like this should be buyable in the cattlelog for a very high price.

**Comment by chandler14362** [comment]
Nope nope nope. Never happening.
