### ISSUE TITLE
Remove Yin and Yang.

### ISSUE THREAD

**Issue by Loudrob** [toontownfellowship/src#48]
We already have the ability to make black and white toons in make a toon. What is the point of Yin and Yang?

**Comment by judge2020** [comment]
The only thing I can think of is turning black/white after making your toon

**Comment by enigmeow** [comment]
amusingly, it seems like people instead want to switch back to colors..

**Comment by enigmeow** [comment]
i believe there is a config option to remove yin and yang

**Comment by judge2020** [comment]
@enigmeow found [here](https://github.com/toontownfellowship/src/blob/master/config/general.prc#L120)

**Comment by enigmeow** [comment]
exactly.. :)

**Comment by enigmeow** [comment]
since we established there is a config item, lets close this
