### ISSUE TITLE
Make camera view cogs walking out of elevator

### ISSUE THREAD

**Issue by Loudrob** [toontownfellowship/src#53]
I know this may not be a major issue, but it can actually cause potential crashing if you try to fire a cog while it's walking out of the elevator. Instead of viewing the gag screen while the cogs walk out, it should view the cogs walking out.

**Comment by judge2020** [comment]
Support

**Comment by enigmeow** [comment]
I have always wanted to ask the gods of TTO if the camera angles were deliberate..

Forcing people to pay attention and remember the cards as they were shown for an instant?  I know TTR just fixed this and I have to agree that it probably a good fix.

**Comment by enigmeow** [comment]
We are creating a new feature branch (feature/new-camera-angle) that will address this issue
