### ISSUE TITLE
Addition: Field Offices

### ISSUE THREAD

**Issue by gamesawdrew** [toontownfellowship/src#54]
I have been missing field offices.
I am starting on adding them in and i will submit a pull request when they are complete!

**Comment by ttcloopy** [comment]
Thank you, all contributions are welcome as we are a small team working on a big project with many areas to consider :)  Best of luck!

**Comment by enigmeow** [comment]
that would be great if you could do that!  Yeah, we are pretty limited in resources so the distributed community is what we are depending on

**Comment by gamesawdrew** [comment]
No problem! I'm trying my best right now

**Comment by enigmeow** [comment]
contact me at ebbohknee@skype if you are really working on this..
