### ISSUE TITLE
toontown/rpc

### ISSUE THREAD

**Issue by gamesawdrew** [toontownfellowship/src#63]
So upon downloading the code, running a server with RPC server enabled, and then go to my browser and type localhost:8080, it gives me a 501 not implemented error, any suggestions?

**Comment by mgracer48** [comment]
i have been wondering how to use rpc server wish there was a guide lol

**Comment by enigmeow** [comment]
Here is a example of using it:  https://github.com/toontownfellowship/src/blob/master/tools/rpc-invasions.py

**Comment by gamesawdrew** [comment]
I tried that file, but i get this error:

Traceback (most recent call last):
  File "rpc-invasions.py", line 16, in <module>
    client = Server(sys.argv[1])
IndexError: list index out of range

**Comment by enigmeow** [comment]
python rpc-invasion.py  server-name  rpc-key

**Comment by enigmeow** [comment]
actually, the server secret is arg 1.. the server name is arg 2

**Comment by gamesawdrew** [comment]
Traceback (most recent call last):
  File "rpc-invasions.py", line 16, in <module>
    client = Server(sys.argv[2])
  File "C:\Panda3D-1.9.0\python\lib\site-packages\jsonrpclib\jsonrpc.py", line 1
97, in __init__
    raise IOError('Unsupported JSON-RPC protocol.')
IOError: Unsupported JSON-RPC protocol.

**Comment by mgracer48** [comment]
i get same error

**Comment by enigmeow** [comment]
example server:   http://localhost:8080

**Comment by enigmeow** [comment]
example server:  http://localhost:8080

**Comment by mgracer48** [comment]
ah i see

**Comment by enigmeow** [comment]
you will owe me a clear writeup on how to use rpc when this is done.. :)

**Comment by gamesawdrew** [comment]
Localhost:8080
gives this
501 Not Implemented

**Comment by gamesawdrew** [comment]
oh wait

**Comment by mgracer48** [comment]
[Errno 61] Connection refused i used a random key

**Comment by enigmeow** [comment]
the uber has to be running, the rpc enabled, the rpc set to use that key..

**Comment by gamesawdrew** [comment]
Oh i got it working

**Comment by mgracer48** [comment]
ah ok

**Comment by gamesawdrew** [comment]
What i want to know, is how to do other commands like name accepting and stuff

**Comment by mgracer48** [comment]
and what config do i use for the key in the prc file

**Comment by gamesawdrew** [comment]
rpc-server-secret

**Comment by gamesawdrew** [comment]
so to launch the rpc thing its "python rpc-invasions.py PUT KEY HERE http://localhost:8080

**Comment by enigmeow** [comment]
Those are all depending on the ClientManager code that TTI used which depending on a whole web infrastructure that never got dropped into the github... ie, lost to time and space

TTFS is doing all the name approvals/etc purely via the mysql database.  We only use the rpc code now for invasion calling. 

I need to update it for the more generic case and add some useful mod commands

**Comment by mgracer48** [comment]
question how do u use mysql with astron thought astron didnt have mysql support and also how do i use it with windows :) and is there an easy way to convert yaml into mysql?

**Comment by mgracer48** [comment]
ok so im guessing to use astron you created it with mongodb then you used mysql its a  shame no tutorial for windows for mysql and also would like to convert yaml into mysql

**Comment by enigmeow** [comment]
1) astron is using mongodb.. 
2) the account config is in mysql for easy php access   
3) No idea the windows case.  I run my test servers in a virtual linux box running on my windows box.. :)
4) I don't know of a converter yet .. but it wouldn't be that hard to write..

**Comment by mgracer48** [comment]
ok one more question using fellowship's client servicesmanagerud can i acutally use mongodb ? I mean like using the mongod cmd and then launching astron with it using database named test with right astron configs that you are using

**Comment by gamesawdrew** [comment]
@enigmeow Oh ok

**Comment by enigmeow** [comment]
there are two different mongodb implementations that use mongodb for everything in servicesmanagerud.  The "dev" one might be better tested.  The other one I wrote but never got tested because people changed the requirements on me ...

**Comment by mgracer48** [comment]
so would accountdb-type developer work is that what your about?

**Comment by mgracer48** [comment]
also when i used mongodb and  put the class mongoaccountdb and was using that and got this invalid password format whats going on why am i being rejected ?

**Comment by enigmeow** [comment]
the "dev" mongodb takes a standard username.  The other one (i was writing) takes a username:password.  Both are just starting points that need to be filled out

**Comment by mgracer48** [comment]
ah thank you man

**Comment by mgracer48** [comment]
@enigmeow  can you make a starting guide doc for doing that if you can?

**Comment by mgracer48** [comment]
using mysqldb i get this 
[2015-02-18 17:09:08] INFO: Message Director: Got an incoming connection from 12
7.0.0.1:49636
[2015-02-18 17:09:29] ERROR: Client (78.43.41.120:52992, 1000000000): Ejecting c
lient (122): invalid password format

**Comment by gamesawdrew** [comment]
34 comments, what have i started

**Comment by enigmeow** [comment]
it wants a name:pass in the generic case.  But, you are close!

One of the win32 starter's reads for a name:pass and the other just does name.

**Comment by mgracer48** [comment]
hmm ok where do i specify pass? i do password specify in the login command prompt so there is a login password

**Comment by gabrielfraser223** [comment]
Where do I set the RPC key?

**Comment by mgracer48** [comment]
or how would i set the password can you give an example please

**Comment by mgracer48** [comment]
:OTPClientRepository(warning): Server is booting us out (122): unknown user

**Comment by mgracer48** [comment]
[2015-10-13 12:17:32] ERROR: Client (78.43.41.122:58168, 1000000005): Ejecting client (122): Can't decode this token.

**Comment by mgracer48** [comment]
2015-10-13 11:47:31] ERROR: Client (78.43.41.122:53364, 1000000002): Ejecting client (122): unknown user

**Comment by gamesawdrew** [comment]
I hope u guys know this autist mg is asking this to use for his own server that isn't even ttf code.

**Comment by mgracer48** [comment]
i hope you guys know that drew is butthurt because im asking help from the only nice guy on TTF team,  enigmeow

**Comment by gamesawdrew** [comment]
I hope u guys know that mg is known for being butthurt and that it isn't the same server and that u should figure out ur own problems

**Comment by mgracer48** [comment]
and you should also know drew asked for help with rpc for his own server ;)

**Comment by gamesawdrew** [comment]
dipshit cuz it was on the same source code...

**Comment by mgracer48** [comment]
dipshit and we are using the same database as TTF is using

**Comment by gamesawdrew** [comment]
no ur not.
autism is so real

**Comment by mgracer48** [comment]
STFU and yes we are, we are using mysql same fellowship is idiot
