### ISSUE TITLE
Bugs/issues: Mod panel

### ISSUE THREAD

**Issue by judge2020** [toontownfellowship/src#66]
1. When an tilde is not typed before the magic word (in the magic word box) the client crashes. To fix I  suggest to just send an open chat message of whatever's in the box so if there's no tilde it'll just say the word.
![image](http://i.gyazo.com/6f34d49255fe70102048a378a63f2838.gif)
traceback: http://pastebin.com/42saAfni

2. After typing a letter in any box, the next letters go into your speech box until you click the box a second time. To fix i suggest maybe disabling the chat box when creating a word, and re-enabling when accept is clicked
![image](http://i.gyazo.com/84c6dfb688cb075acd675b416693a0e0.gif)

3. No way to delete an button (this is why there's so many buttons in the gif's above). Maybe put a trash can icon in the bottom-right of the screen above the shticker book?

4. No way to cancel creating a button. put a cancel button next to the accept button?

**Comment by chandler14362** [comment]
For number 3: Press the middle mouse key while hovering over the button.

Ill work on fixing the rest of the issues.
