### ISSUE TITLE
create an rpc document

### ISSUE THREAD

**Issue by mgracer48** [toontownfellowship/src#67]
Its a little confusing on how it works it would be great if you could create a doc for it and setting it up

**Comment by enigmeow** [comment]
Here is a example of using it

https://github.com/toontownfellowship/src/blob/master/tools/rpc-invasions.py

I will cobble together a simple doc..

**Comment by gamesawdrew** [comment]
@enigmeow Ok thanks

**Comment by enigmeow** [comment]
I think we beat this to death in another issue (toontown/rpc)
