### ISSUE TITLE
Building Client

### ISSUE THREAD

**Issue by gamesawdrew** [toontownfellowship/src#69]
So i try the build_client, i do everything the doc says, but i get a bunch of errors. Please tell me how to do the build client process right from the beginning to end! Thank you!

**Comment by judge2020** [comment]
Please read the doc. It says to get 'infinite cypher' from a dev

**Comment by enigmeow** [comment]
we have not documented how TTF builds a client..  it is the only even remote security we have..

sorry

**Comment by judge2020** [comment]
Yes @enigmeow , i meant from the old tti's doc for building client

**Comment by gamesawdrew** [comment]
Oh. well im smart, i need to prepare client first...

**Comment by gamesawdrew** [comment]
Do you think you could help me?
Me and some of my friends are planning on bringing up a server! We already have the code and stuff ready, we just need help building it, dont worry, we wont try to compete with you ;)

**Comment by CrazyClyde** [comment]
issue #69 lolol

**Comment by enigmeow** [comment]
What are your requirements?  That it be injection proof?  That users cannot use modified clients?

If you table these requirements, its pretty easy...

**Comment by gamesawdrew** [comment]
Ya, Pretty much

**Comment by gamesawdrew** [comment]
When i use build_client.py i get this: http://pastebin.com/zq5E9bpp

**Comment by ToontownMichael** [comment]
Will the infinitecipher be avaliable?

**Comment by xJollibee** [comment]
@enigmeow Not trying to be mean but, I think you should forget about security and work on new content. You need to keep your fanbase and even expand it. Security won't matter in a year when nobody is playing it because of no new content.

**Comment by kevman95** [comment]
You wont get infinite cipher  before i am even dead. LOL.

**Comment by Loudrob** [comment]
@kevman95 based on whats happening, i am excited how soon the infinite cipher is coming

**Comment by xJollibee** [comment]
LOL @Loudrob I'm excited to!

**Comment by joshsora** [comment]
This chat has given me aids.
TTF has given me aids.
Kill it.
