### ISSUE TITLE
Enhancement: Nametag size increases by distance.

### ISSUE THREAD

**Issue by Loudrob** [toontownfellowship/src#85]
One thing I have always wondered about these private servers was: Why don't the nametags grow as the character gets farther away like they did in Toontown Online? Here's an example of Disney's nametags from a distance:

![bxafbgv](https://cloud.githubusercontent.com/assets/8785030/6314213/0c132040-b9a4-11e4-8c59-42dcfc5120a2.png)

And here's the current nametags. Very hard to see or click on from this distance:

![pq5hdfi](https://cloud.githubusercontent.com/assets/8785030/6314215/25585a7a-b9a4-11e4-9ff5-08665fedeee8.png)

It would be pretty nice if we were able to make the nametags grow as the character gets farther away.

**Comment by gamesawdrew** [comment]
speaking of "Very hard to see" I CANT SEE THOSE PICTURES lol

**Comment by judge2020** [comment]
this'd be a nice feature.

**Comment by enigmeow** [comment]
we have a dev working on this now.. :)

**Comment by Keatonn** [comment]
Enigmeow and I have fixed this, it should be fixed in the next update :).

**Comment by judge2020** [comment]
Nice! (close please)
