### ISSUE TITLE
cant see tall cogs' level 

### ISSUE THREAD

**Issue by mgracer48** [toontownfellowship/src#99]
I suggest we implement  a gui for levels or fix the camera

**Comment by gamesawdrew** [comment]
If we did the gui, we would have to make it unique, not exactly the same as
ttr

**Comment by mgracer48** [comment]
your right

**Comment by starsky135** [comment]
It would be more unique/effective if the camera angles were fixed.

**Comment by Chandler255** [comment]
@starsky135 So, you suggest we zoom the camera out a bit so you would be able to see the levels?

**Comment by enigmeow** [comment]
i assume this is similar to the changes recently put into TTR?

**Comment by starsky135** [comment]
@Chandler255 Yeah pretty much, newer MMOs seem to have a camera angle that is angled from the side of the players, but that could be an issue because the streets are pretty narrow.

**Comment by gamesawdrew** [comment]
i would think, have that side angle, but only if u click on something on
the battle menu that will move the camera smoothly over to the side to see
the levels temporarily, the problem with making the battle always like
that, is when you use a gag that affects 1 cog when there are moer than 1,
the arrows won't point correctly...

**Comment by enigmeow** [comment]
We are creating a new feature branch (feature/new-camera-angle) that will address this issue
